"""Sprint 4: Menu domain — allergens, dietary profiles, cooking methods, badges, seals, ingredients.

Extends existing tables and creates new junction tables for the menu domain.

Revision ID: 004
Revises: 003
Create Date: 2026-03-27
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "004"
down_revision: Union[str, None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ═══════════════════════════════════════════════════════════════════
    # 1. ALTER existing tables
    # ═══════════════════════════════════════════════════════════════════

    # ── 1a. Allergens ──
    # Drop old unique constraints (autogenerated names)
    op.drop_constraint("allergens_name_key", "allergens", type_="unique")
    op.drop_constraint("allergens_code_key", "allergens", type_="unique")

    # Add new columns
    op.add_column("allergens", sa.Column("icon", sa.String(50), nullable=True))
    op.add_column("allergens", sa.Column("is_system", sa.Boolean(), nullable=False, server_default="false"))
    op.add_column("allergens", sa.Column("tenant_id", sa.BigInteger(), nullable=True))

    # Drop old icon_url (replaced by icon)
    op.drop_column("allergens", "icon_url")

    # Widen code column 20 -> 50
    op.alter_column("allergens", "code", type_=sa.String(50), existing_type=sa.String(20))

    # Add FK for tenant_id
    op.create_foreign_key(
        "fk_allergens_tenant_id", "allergens", "tenants",
        ["tenant_id"], ["id"], ondelete="CASCADE",
    )
    op.create_index("ix_allergens_tenant_id", "allergens", ["tenant_id"])
    op.create_index("ix_allergens_code", "allergens", ["code"])

    # New unique constraint: (code, tenant_id)
    op.create_unique_constraint("uq_allergens_code_tenant", "allergens", ["code", "tenant_id"])

    # Check: system allergens have no tenant
    op.create_check_constraint(
        "ck_allergens_system_no_tenant", "allergens",
        "is_system = false OR tenant_id IS NULL",
    )

    # Mark existing allergens as system
    op.execute("UPDATE allergens SET is_system = true WHERE tenant_id IS NULL")

    # ── 1b. ProductAllergens ──
    op.add_column("product_allergens", sa.Column("presence_type", sa.String(20), nullable=False, server_default="contains"))
    op.add_column("product_allergens", sa.Column("risk_level", sa.String(20), nullable=False, server_default="moderate"))
    op.add_column("product_allergens", sa.Column("notes", sa.Text(), nullable=True))

    # Migrate: old severity -> presence_type (keep what maps, default rest to 'contains')
    op.execute("""
        UPDATE product_allergens SET presence_type = severity
        WHERE severity IN ('contains', 'may_contain', 'free_of')
    """)
    op.execute("""
        UPDATE product_allergens SET presence_type = 'contains'
        WHERE severity NOT IN ('contains', 'may_contain', 'free_of')
    """)

    op.drop_column("product_allergens", "severity")

    op.create_check_constraint(
        "ck_product_allergens_free_of_low_risk", "product_allergens",
        "presence_type != 'free_of' OR risk_level = 'low'",
    )

    # Upgrade FKs to CASCADE
    op.drop_constraint("product_allergens_product_id_fkey", "product_allergens", type_="foreignkey")
    op.drop_constraint("product_allergens_allergen_id_fkey", "product_allergens", type_="foreignkey")
    op.create_foreign_key(
        "product_allergens_product_id_fkey", "product_allergens", "products",
        ["product_id"], ["id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "product_allergens_allergen_id_fkey", "product_allergens", "allergens",
        ["allergen_id"], ["id"], ondelete="CASCADE",
    )

    # ── 1c. BranchProducts ──
    op.add_column("branch_products", sa.Column("price_cents", sa.Integer(), nullable=True))
    op.add_column("branch_products", sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"))

    # Migrate price_override_cents -> price_cents
    op.execute("UPDATE branch_products SET price_cents = price_override_cents")

    op.drop_constraint("ck_branch_products_override_positive", "branch_products", type_="check")
    op.drop_column("branch_products", "price_override_cents")
    op.drop_column("branch_products", "stock_quantity")

    op.create_check_constraint(
        "ck_branch_products_price_positive", "branch_products",
        "price_cents IS NULL OR price_cents >= 0",
    )

    # Upgrade FKs to CASCADE
    op.drop_constraint("branch_products_branch_id_fkey", "branch_products", type_="foreignkey")
    op.drop_constraint("branch_products_product_id_fkey", "branch_products", type_="foreignkey")
    op.create_foreign_key(
        "branch_products_branch_id_fkey", "branch_products", "branches",
        ["branch_id"], ["id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "branch_products_product_id_fkey", "branch_products", "products",
        ["product_id"], ["id"], ondelete="CASCADE",
    )

    # ── 1d. CookingMethods ──
    op.add_column("cooking_methods", sa.Column("code", sa.String(50), nullable=True))
    op.add_column("cooking_methods", sa.Column("icon", sa.String(50), nullable=True))
    op.add_column("cooking_methods", sa.Column("is_system", sa.Boolean(), nullable=False, server_default="false"))

    # Backfill code from name
    op.execute("UPDATE cooking_methods SET code = LOWER(REPLACE(REPLACE(REPLACE(name, ' ', '_'), 'á', 'a'), 'ó', 'o'))")
    op.alter_column("cooking_methods", "code", nullable=False)
    op.create_index("ix_cooking_methods_code", "cooking_methods", ["code"])

    # Drop old unique, make tenant_id nullable, drop/re-create FK with CASCADE
    op.drop_constraint("uq_cooking_methods_tenant_name", "cooking_methods", type_="unique")
    op.drop_constraint("cooking_methods_tenant_id_fkey", "cooking_methods", type_="foreignkey")
    op.alter_column("cooking_methods", "tenant_id", nullable=True)
    op.create_foreign_key(
        "cooking_methods_tenant_id_fkey", "cooking_methods", "tenants",
        ["tenant_id"], ["id"], ondelete="CASCADE",
    )

    op.create_unique_constraint("uq_cooking_methods_code_tenant", "cooking_methods", ["code", "tenant_id"])
    op.create_check_constraint("ck_cooking_methods_system_no_tenant", "cooking_methods", "is_system = false OR tenant_id IS NULL")

    # ── 1e. FlavorProfiles ──
    op.add_column("flavor_profiles", sa.Column("code", sa.String(50), nullable=True))
    op.add_column("flavor_profiles", sa.Column("icon", sa.String(50), nullable=True))
    op.add_column("flavor_profiles", sa.Column("is_system", sa.Boolean(), nullable=False, server_default="false"))

    op.execute("UPDATE flavor_profiles SET code = LOWER(REPLACE(REPLACE(REPLACE(name, ' ', '_'), 'á', 'a'), 'ó', 'o'))")
    op.alter_column("flavor_profiles", "code", nullable=False)
    op.create_index("ix_flavor_profiles_code", "flavor_profiles", ["code"])

    op.drop_constraint("uq_flavor_profiles_tenant_name", "flavor_profiles", type_="unique")
    op.drop_constraint("flavor_profiles_tenant_id_fkey", "flavor_profiles", type_="foreignkey")
    op.alter_column("flavor_profiles", "tenant_id", nullable=True)
    op.create_foreign_key(
        "flavor_profiles_tenant_id_fkey", "flavor_profiles", "tenants",
        ["tenant_id"], ["id"], ondelete="CASCADE",
    )

    op.create_unique_constraint("uq_flavor_profiles_code_tenant", "flavor_profiles", ["code", "tenant_id"])
    op.create_check_constraint("ck_flavor_profiles_system_no_tenant", "flavor_profiles", "is_system = false OR tenant_id IS NULL")

    # ── 1f. TextureProfiles ──
    op.add_column("texture_profiles", sa.Column("code", sa.String(50), nullable=True))
    op.add_column("texture_profiles", sa.Column("icon", sa.String(50), nullable=True))
    op.add_column("texture_profiles", sa.Column("is_system", sa.Boolean(), nullable=False, server_default="false"))

    op.execute("UPDATE texture_profiles SET code = LOWER(REPLACE(REPLACE(REPLACE(name, ' ', '_'), 'á', 'a'), 'ó', 'o'))")
    op.alter_column("texture_profiles", "code", nullable=False)
    op.create_index("ix_texture_profiles_code", "texture_profiles", ["code"])

    op.drop_constraint("uq_texture_profiles_tenant_name", "texture_profiles", type_="unique")
    op.drop_constraint("texture_profiles_tenant_id_fkey", "texture_profiles", type_="foreignkey")
    op.alter_column("texture_profiles", "tenant_id", nullable=True)
    op.create_foreign_key(
        "texture_profiles_tenant_id_fkey", "texture_profiles", "tenants",
        ["tenant_id"], ["id"], ondelete="CASCADE",
    )

    op.create_unique_constraint("uq_texture_profiles_code_tenant", "texture_profiles", ["code", "tenant_id"])
    op.create_check_constraint("ck_texture_profiles_system_no_tenant", "texture_profiles", "is_system = false OR tenant_id IS NULL")

    # ── 1g. Badges ──
    # Badges already have: name, color, icon, tenant_id (NOT NULL)
    op.drop_constraint("uq_badges_tenant_name", "badges", type_="unique")

    op.add_column("badges", sa.Column("code", sa.String(50), nullable=True))
    op.add_column("badges", sa.Column("is_system", sa.Boolean(), nullable=False, server_default="false"))

    # Backfill code
    op.execute("UPDATE badges SET code = LOWER(REPLACE(REPLACE(REPLACE(name, ' ', '_'), 'á', 'a'), 'ó', 'o'))")
    op.alter_column("badges", "code", nullable=False)
    op.create_index("ix_badges_code", "badges", ["code"])

    # Make tenant_id nullable, drop/re-create FK
    op.drop_constraint("badges_tenant_id_fkey", "badges", type_="foreignkey")
    op.alter_column("badges", "tenant_id", nullable=True)
    op.create_foreign_key(
        "badges_tenant_id_fkey", "badges", "tenants",
        ["tenant_id"], ["id"], ondelete="CASCADE",
    )

    # Ensure color is NOT NULL
    op.execute("UPDATE badges SET color = '#000000' WHERE color IS NULL")
    op.alter_column("badges", "color", nullable=False, server_default="#000000")

    op.create_unique_constraint("uq_badges_code_tenant", "badges", ["code", "tenant_id"])
    op.create_check_constraint("ck_badges_system_no_tenant", "badges", "is_system = false OR tenant_id IS NULL")

    # ── 1h. Seals ──
    # Seals have: name, icon_url, description, tenant_id (NOT NULL)
    op.drop_constraint("uq_seals_tenant_name", "seals", type_="unique")

    op.add_column("seals", sa.Column("code", sa.String(50), nullable=True))
    op.add_column("seals", sa.Column("color", sa.String(7), nullable=False, server_default="#000000"))
    op.add_column("seals", sa.Column("icon", sa.String(50), nullable=True))
    op.add_column("seals", sa.Column("is_system", sa.Boolean(), nullable=False, server_default="false"))

    # Backfill code
    op.execute("UPDATE seals SET code = LOWER(REPLACE(REPLACE(REPLACE(name, ' ', '_'), 'á', 'a'), 'ó', 'o'))")
    op.alter_column("seals", "code", nullable=False)
    op.create_index("ix_seals_code", "seals", ["code"])

    # Drop icon_url (replaced by icon)
    op.drop_column("seals", "icon_url")

    # Make tenant_id nullable, drop/re-create FK
    op.drop_constraint("seals_tenant_id_fkey", "seals", type_="foreignkey")
    op.alter_column("seals", "tenant_id", nullable=True)
    op.create_foreign_key(
        "seals_tenant_id_fkey", "seals", "tenants",
        ["tenant_id"], ["id"], ondelete="CASCADE",
    )

    op.create_unique_constraint("uq_seals_code_tenant", "seals", ["code", "tenant_id"])
    op.create_check_constraint("ck_seals_system_no_tenant", "seals", "is_system = false OR tenant_id IS NULL")

    # ── 1i. Products: add ARRAY columns and short_description ──
    op.add_column("products", sa.Column("short_description", sa.String(500), nullable=True))
    op.add_column("products", sa.Column("flavor_profiles_array", sa.ARRAY(sa.String(20)), nullable=True, server_default="{}"))
    op.add_column("products", sa.Column("texture_profiles_array", sa.ARRAY(sa.String(20)), nullable=True, server_default="{}"))

    # ═══════════════════════════════════════════════════════════════════
    # 2. CREATE new tables
    # ═══════════════════════════════════════════════════════════════════

    _audit_cols = [
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
    ]

    # ── 2a. AllergenCrossReaction ──
    op.create_table(
        "allergen_cross_reactions",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("allergen_id", sa.BigInteger(), sa.ForeignKey("allergens.id", ondelete="CASCADE"), nullable=False),
        sa.Column("related_allergen_id", sa.BigInteger(), sa.ForeignKey("allergens.id", ondelete="CASCADE"), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False),
        *_audit_cols,
        sa.UniqueConstraint("allergen_id", "related_allergen_id", name="uq_allergen_cross_reactions_pair"),
        sa.CheckConstraint("allergen_id < related_allergen_id", name="ck_allergen_cross_reactions_canonical_order"),
    )
    op.create_index("ix_allergen_cross_reactions_allergen_id", "allergen_cross_reactions", ["allergen_id"])
    op.create_index("ix_allergen_cross_reactions_related_allergen_id", "allergen_cross_reactions", ["related_allergen_id"])

    # ── 2b. DietaryProfile ──
    op.create_table(
        "dietary_profiles",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("code", sa.String(50), nullable=False),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(50), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("tenant_id", sa.BigInteger(), sa.ForeignKey("tenants.id", ondelete="CASCADE"), nullable=True),
        *_audit_cols,
        sa.UniqueConstraint("code", "tenant_id", name="uq_dietary_profiles_code_tenant"),
        sa.CheckConstraint("is_system = false OR tenant_id IS NULL", name="ck_dietary_profiles_system_no_tenant"),
    )
    op.create_index("ix_dietary_profiles_code", "dietary_profiles", ["code"])
    op.create_index("ix_dietary_profiles_tenant_id", "dietary_profiles", ["tenant_id"])

    # ── 2c. ProductDietaryProfile ──
    op.create_table(
        "product_dietary_profiles",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("product_id", sa.BigInteger(), sa.ForeignKey("products.id", ondelete="CASCADE"), nullable=False),
        sa.Column("dietary_profile_id", sa.BigInteger(), sa.ForeignKey("dietary_profiles.id", ondelete="CASCADE"), nullable=False),
        *_audit_cols,
        sa.UniqueConstraint("product_id", "dietary_profile_id", name="uq_product_dietary_profiles_product_profile"),
    )
    op.create_index("ix_product_dietary_profiles_product_id", "product_dietary_profiles", ["product_id"])
    op.create_index("ix_product_dietary_profiles_dietary_profile_id", "product_dietary_profiles", ["dietary_profile_id"])

    # ── 2d. ProductCookingMethod ──
    op.create_table(
        "product_cooking_methods",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("product_id", sa.BigInteger(), sa.ForeignKey("products.id", ondelete="CASCADE"), nullable=False),
        sa.Column("cooking_method_id", sa.BigInteger(), sa.ForeignKey("cooking_methods.id", ondelete="CASCADE"), nullable=False),
        *_audit_cols,
        sa.UniqueConstraint("product_id", "cooking_method_id", name="uq_product_cooking_methods_product_method"),
    )
    op.create_index("ix_product_cooking_methods_product_id", "product_cooking_methods", ["product_id"])
    op.create_index("ix_product_cooking_methods_cooking_method_id", "product_cooking_methods", ["cooking_method_id"])

    # ── 2e. ProductBadge ──
    op.create_table(
        "product_badges",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("product_id", sa.BigInteger(), sa.ForeignKey("products.id", ondelete="CASCADE"), nullable=False),
        sa.Column("badge_id", sa.BigInteger(), sa.ForeignKey("badges.id", ondelete="CASCADE"), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        *_audit_cols,
        sa.UniqueConstraint("product_id", "badge_id", name="uq_product_badges_product_badge"),
    )
    op.create_index("ix_product_badges_product_id", "product_badges", ["product_id"])
    op.create_index("ix_product_badges_badge_id", "product_badges", ["badge_id"])

    # ── 2f. ProductSeal ──
    op.create_table(
        "product_seals",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("product_id", sa.BigInteger(), sa.ForeignKey("products.id", ondelete="CASCADE"), nullable=False),
        sa.Column("seal_id", sa.BigInteger(), sa.ForeignKey("seals.id", ondelete="CASCADE"), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        *_audit_cols,
        sa.UniqueConstraint("product_id", "seal_id", name="uq_product_seals_product_seal"),
    )
    op.create_index("ix_product_seals_product_id", "product_seals", ["product_id"])
    op.create_index("ix_product_seals_seal_id", "product_seals", ["seal_id"])

    # ── 2g. ProductIngredient ──
    op.create_table(
        "product_ingredients",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("product_id", sa.BigInteger(), sa.ForeignKey("products.id", ondelete="CASCADE"), nullable=False),
        sa.Column("ingredient_id", sa.BigInteger(), sa.ForeignKey("ingredients.id", ondelete="SET NULL"), nullable=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("quantity", sa.Numeric(10, 3), nullable=False),
        sa.Column("unit", sa.String(10), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_optional", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("notes", sa.Text(), nullable=True),
        *_audit_cols,
        sa.UniqueConstraint("product_id", "sort_order", name="uq_product_ingredients_product_sort"),
        sa.CheckConstraint("quantity > 0", name="ck_product_ingredients_quantity_positive"),
    )
    op.create_index("ix_product_ingredients_product_id", "product_ingredients", ["product_id"])

    # ═══════════════════════════════════════════════════════════════════
    # 3. Data migration: copy cooking_method_id FK to junction table
    # ═══════════════════════════════════════════════════════════════════
    op.execute("""
        INSERT INTO product_cooking_methods (product_id, cooking_method_id)
        SELECT id, cooking_method_id FROM products
        WHERE cooking_method_id IS NOT NULL
        ON CONFLICT DO NOTHING
    """)


def downgrade() -> None:
    # ═══════════════════════════════════════════════════════════════════
    # 1. Drop new tables (reverse order)
    # ═══════════════════════════════════════════════════════════════════
    op.drop_table("product_ingredients")
    op.drop_table("product_seals")
    op.drop_table("product_badges")
    op.drop_table("product_cooking_methods")
    op.drop_table("product_dietary_profiles")
    op.drop_table("dietary_profiles")
    op.drop_table("allergen_cross_reactions")

    # ═══════════════════════════════════════════════════════════════════
    # 2. Revert Products
    # ═══════════════════════════════════════════════════════════════════
    op.drop_column("products", "texture_profiles_array")
    op.drop_column("products", "flavor_profiles_array")
    op.drop_column("products", "short_description")

    # ═══════════════════════════════════════════════════════════════════
    # 3. Revert Seals
    # ═══════════════════════════════════════════════════════════════════
    op.drop_constraint("ck_seals_system_no_tenant", "seals", type_="check")
    op.drop_constraint("uq_seals_code_tenant", "seals", type_="unique")
    op.drop_constraint("seals_tenant_id_fkey", "seals", type_="foreignkey")
    op.alter_column("seals", "tenant_id", nullable=False)
    op.create_foreign_key("seals_tenant_id_fkey", "seals", "tenants", ["tenant_id"], ["id"])
    op.drop_index("ix_seals_code", table_name="seals")
    op.drop_column("seals", "is_system")
    op.drop_column("seals", "icon")
    op.drop_column("seals", "color")
    op.drop_column("seals", "code")
    op.add_column("seals", sa.Column("icon_url", sa.String(500), nullable=True))
    op.create_unique_constraint("uq_seals_tenant_name", "seals", ["tenant_id", "name"])

    # ═══════════════════════════════════════════════════════════════════
    # 4. Revert Badges
    # ═══════════════════════════════════════════════════════════════════
    op.drop_constraint("ck_badges_system_no_tenant", "badges", type_="check")
    op.drop_constraint("uq_badges_code_tenant", "badges", type_="unique")
    op.drop_constraint("badges_tenant_id_fkey", "badges", type_="foreignkey")
    op.alter_column("badges", "color", nullable=True, server_default=None)
    op.alter_column("badges", "tenant_id", nullable=False)
    op.create_foreign_key("badges_tenant_id_fkey", "badges", "tenants", ["tenant_id"], ["id"])
    op.drop_index("ix_badges_code", table_name="badges")
    op.drop_column("badges", "is_system")
    op.drop_column("badges", "code")
    op.create_unique_constraint("uq_badges_tenant_name", "badges", ["tenant_id", "name"])

    # ═══════════════════════════════════════════════════════════════════
    # 5. Revert TextureProfiles
    # ═══════════════════════════════════════════════════════════════════
    op.drop_constraint("ck_texture_profiles_system_no_tenant", "texture_profiles", type_="check")
    op.drop_constraint("uq_texture_profiles_code_tenant", "texture_profiles", type_="unique")
    op.drop_constraint("texture_profiles_tenant_id_fkey", "texture_profiles", type_="foreignkey")
    op.alter_column("texture_profiles", "tenant_id", nullable=False)
    op.create_foreign_key("texture_profiles_tenant_id_fkey", "texture_profiles", "tenants", ["tenant_id"], ["id"])
    op.drop_index("ix_texture_profiles_code", table_name="texture_profiles")
    op.drop_column("texture_profiles", "is_system")
    op.drop_column("texture_profiles", "icon")
    op.drop_column("texture_profiles", "code")
    op.create_unique_constraint("uq_texture_profiles_tenant_name", "texture_profiles", ["tenant_id", "name"])

    # ═══════════════════════════════════════════════════════════════════
    # 6. Revert FlavorProfiles
    # ═══════════════════════════════════════════════════════════════════
    op.drop_constraint("ck_flavor_profiles_system_no_tenant", "flavor_profiles", type_="check")
    op.drop_constraint("uq_flavor_profiles_code_tenant", "flavor_profiles", type_="unique")
    op.drop_constraint("flavor_profiles_tenant_id_fkey", "flavor_profiles", type_="foreignkey")
    op.alter_column("flavor_profiles", "tenant_id", nullable=False)
    op.create_foreign_key("flavor_profiles_tenant_id_fkey", "flavor_profiles", "tenants", ["tenant_id"], ["id"])
    op.drop_index("ix_flavor_profiles_code", table_name="flavor_profiles")
    op.drop_column("flavor_profiles", "is_system")
    op.drop_column("flavor_profiles", "icon")
    op.drop_column("flavor_profiles", "code")
    op.create_unique_constraint("uq_flavor_profiles_tenant_name", "flavor_profiles", ["tenant_id", "name"])

    # ═══════════════════════════════════════════════════════════════════
    # 7. Revert CookingMethods
    # ═══════════════════════════════════════════════════════════════════
    op.drop_constraint("ck_cooking_methods_system_no_tenant", "cooking_methods", type_="check")
    op.drop_constraint("uq_cooking_methods_code_tenant", "cooking_methods", type_="unique")
    op.drop_constraint("cooking_methods_tenant_id_fkey", "cooking_methods", type_="foreignkey")
    op.alter_column("cooking_methods", "tenant_id", nullable=False)
    op.create_foreign_key("cooking_methods_tenant_id_fkey", "cooking_methods", "tenants", ["tenant_id"], ["id"])
    op.drop_index("ix_cooking_methods_code", table_name="cooking_methods")
    op.drop_column("cooking_methods", "is_system")
    op.drop_column("cooking_methods", "icon")
    op.drop_column("cooking_methods", "code")
    op.create_unique_constraint("uq_cooking_methods_tenant_name", "cooking_methods", ["tenant_id", "name"])

    # ═══════════════════════════════════════════════════════════════════
    # 8. Revert BranchProducts
    # ═══════════════════════════════════════════════════════════════════
    op.drop_constraint("ck_branch_products_price_positive", "branch_products", type_="check")
    op.drop_constraint("branch_products_product_id_fkey", "branch_products", type_="foreignkey")
    op.drop_constraint("branch_products_branch_id_fkey", "branch_products", type_="foreignkey")
    op.create_foreign_key("branch_products_branch_id_fkey", "branch_products", "branches", ["branch_id"], ["id"])
    op.create_foreign_key("branch_products_product_id_fkey", "branch_products", "products", ["product_id"], ["id"])
    op.add_column("branch_products", sa.Column("stock_quantity", sa.Integer(), nullable=True))
    op.add_column("branch_products", sa.Column("price_override_cents", sa.Integer(), nullable=True))
    op.execute("UPDATE branch_products SET price_override_cents = price_cents")
    op.drop_column("branch_products", "sort_order")
    op.drop_column("branch_products", "price_cents")
    op.create_check_constraint(
        "ck_branch_products_override_positive", "branch_products",
        "price_override_cents >= 0 OR price_override_cents IS NULL",
    )

    # ═══════════════════════════════════════════════════════════════════
    # 9. Revert ProductAllergens
    # ═══════════════════════════════════════════════════════════════════
    op.drop_constraint("ck_product_allergens_free_of_low_risk", "product_allergens", type_="check")
    op.drop_constraint("product_allergens_allergen_id_fkey", "product_allergens", type_="foreignkey")
    op.drop_constraint("product_allergens_product_id_fkey", "product_allergens", type_="foreignkey")
    op.create_foreign_key("product_allergens_product_id_fkey", "product_allergens", "products", ["product_id"], ["id"])
    op.create_foreign_key("product_allergens_allergen_id_fkey", "product_allergens", "allergens", ["allergen_id"], ["id"])
    op.add_column("product_allergens", sa.Column("severity", sa.String(20), nullable=False, server_default="contains"))
    op.execute("UPDATE product_allergens SET severity = presence_type")
    op.drop_column("product_allergens", "notes")
    op.drop_column("product_allergens", "risk_level")
    op.drop_column("product_allergens", "presence_type")

    # ═══════════════════════════════════════════════════════════════════
    # 10. Revert Allergens
    # ═══════════════════════════════════════════════════════════════════
    op.drop_constraint("ck_allergens_system_no_tenant", "allergens", type_="check")
    op.drop_constraint("uq_allergens_code_tenant", "allergens", type_="unique")
    op.drop_index("ix_allergens_code", table_name="allergens")
    op.drop_index("ix_allergens_tenant_id", table_name="allergens")
    op.drop_constraint("fk_allergens_tenant_id", "allergens", type_="foreignkey")
    op.drop_column("allergens", "tenant_id")
    op.drop_column("allergens", "is_system")
    op.drop_column("allergens", "icon")
    op.add_column("allergens", sa.Column("icon_url", sa.String(500), nullable=True))
    op.alter_column("allergens", "code", type_=sa.String(20), existing_type=sa.String(50))
    op.create_unique_constraint("allergens_code_key", "allergens", ["code"])
    op.create_unique_constraint("allergens_name_key", "allergens", ["name"])
